### ISSUE TITLE
Improve DOGM API

### ISSUE THREAD

**Issue by TheCodez** [TheCodez/dynamic-occupancy-grid-map#51]
First step is to split the measurement grid calculation from the DOGM class, see https://github.com/TheCodez/dynamic-occupancy-grid-map/issues/8

Currently we have:
```cpp
void updatePose(float new_x, float new_y);
void updateMeasurementGrid(const std::vector<float>& measurements);
void updateGrid(float dt);
```

After the split we could have something like:
```cpp
void updatePose(float new_x, float new_y);
void updateGrid(MeasurementCell* meas_grid, float dt);
```

The question is if this API is viable for user code.

Note:
The `updatePose` method moves the grid map of timestep k-1 to the new location of the measurement grid at time k (ego motion compensation).

**Comment by cbachhuber** [comment]
Your proposed API is definitely a step in the right direction :+1: 

I also like giving `meas_grid` as input to `updateParticleFilter`. This is what I as user would expect after reading Nuss' paper: I update my grid with a new measurement grid.

Maybe renaming `updateParticleFilter` to e.g. `updateGrid` makes sense. That's because the particle filter is only (a big) part of your entire grid mapping function. What do you think about this?

**Comment by TheCodez** [comment]
Yes, I agree. The particle filter is only the internal system that updates the grid.

**Comment by cbachhuber** [comment]
Good. Are you working on this or should I give it a shot?

**Comment by TheCodez** [comment]
I'm working on this. But thanks :)
