### ISSUE TITLE
Implementation differing from paper and dogma?

### ISSUE THREAD

**Issue by cbachhuber** [TheCodez/dynamic-occupancy-grid-map#58]
For the calculation of the normalization component of an unassociated measurement ([mu_UA](https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/src/kernel/update_persistent_particles.cu#L72)) in [calc_norm_unassoc()](https://github.com/TheCodez/dynamic-occupancy-grid-map/blob/master/dogm/src/kernel/update_persistent_particles.cu#L21) you are using persistent_occ_mass (rho_p) divided by `occ_mass`. 

In [the paper](https://arxiv.org/pdf/1605.02406.pdf), equation 63 states mu_UA = rho_p / `pred_occ_mass`. In equation 63, the `pred_occ_mass` is the sum of weights originally predicted into the cell, while the `occ_mass` in your implementation is the result after dempster's rule of combination of the predicted mass and the measured mass. [Mitkina's python implementation](https://github.com/mitkina/dogma/blob/master/ParticleFilter/PersistentParticleUpdate.py#L50) does it as in the paper.

Is there a reason for you doing that differently?

**Comment by TheCodez** [comment]
Good catch! Thank you 👍 
Fixed in https://github.com/TheCodez/dynamic-occupancy-grid-map/commit/010301cd5f5a1b414082ffb9f495bd2f6d492786

Given that we only have laser measurements with an association probability of 1 and no radar measurements which would have varying pA, this has no impact on the current implementation as we only have associated particles.

**Comment by cbachhuber** [comment]
Great, that was quick! Thanks :)
